---
new_page_extension: md
auto_deploy: false
admin_path: "/admin"
webhook_url: http://example.com/webhook
sections:
- type: directory
  path: content
  label: Pages
  create: all
  match: "**/*"
- type: directory
  path: content/posts
  label: Posts
  create: all
  match: "**/*"
  templates:
  - posts
- type: directory
  path: content/secrets
  label: Content/secrets
  create: all
  match: "**/*"
  hidden: true
- type: directory
  path: content/products
  label: Products
  create: none
  match: "**/*"
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
